(function(){var h={},mt={},c={id:"6d83f082b8fe8f41ecc67eba5509d6e9",dm:["apistore.baidu.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,r=!1;mt.h={};mt.h.va=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.ya=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,e){var g;e.D&&(g=new Date,g.setTime(g.getTime()+e.D));document.cookie=a+"="+b+(e.domain?"; domain="+e.domain:"")+(e.path?"; path="+e.path:"")+(g?"; expires="+g.toGMTString():"")+(e.Na?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.o={};mt.o.Ga=function(a){return document.getElementById(a)};mt.o.ha=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return q};
(mt.o.wa=function(){function a(){if(!a.t){a.t=p;for(var b=0,e=g.length;b<e;b++)g[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(g){setTimeout(b,1);return}a()}var e=r,g=[],k;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,r);a()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),a())});(function(){if(!e)if(e=p,"complete"===document.readyState)a.t=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
k,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",k);window.attachEvent("onload",a);var g=r;try{g=window.frameElement==q}catch(n){}document.documentElement.doScroll&&g&&b()}})();return function(b){a.t?b():g.push(b)}}()).t=r;mt.event={};mt.event.d=function(a,b,e){a.attachEvent?a.attachEvent("on"+b,function(b){e.call(a,b)}):a.addEventListener&&a.addEventListener(b,e,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.l={};mt.l.parse=function(){return(new Function('return (" + source + ")'))()};
mt.l.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=e[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(g){switch(typeof g){case "undefined":return"undefined";case "number":return isFinite(g)?String(g):"null";case "string":return a(g);case "boolean":return String(g);
default:if(g===q)return"null";if(g instanceof Array){var e=["["],m=g.length,n,d,f;for(d=0;d<m;d++)switch(f=g[d],typeof f){case "undefined":case "function":case "unknown":break;default:n&&e.push(","),e.push(mt.l.stringify(f)),n=1}e.push("]");return e.join("")}if(g instanceof Date)return'"'+g.getFullYear()+"-"+b(g.getMonth()+1)+"-"+b(g.getDate())+"T"+b(g.getHours())+":"+b(g.getMinutes())+":"+b(g.getSeconds())+'"';n=["{"];d=mt.l.stringify;for(m in g)if(Object.prototype.hasOwnProperty.call(g,m))switch(f=
g[m],typeof f){case "undefined":case "unknown":case "function":break;default:e&&n.push(","),e=1,n.push(d(m)+":"+d(f))}n.push("}");return n.join("")}}}();mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ka=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ma=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.B=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,b,e){var g=new Date;g.setTime(g.getTime()+e||31536E6);try{window.localStorage?(b=g.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.B()&&(mt.localStorage.f.expires=g.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),e=a.substring(0,b)-0;if(e&&e>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.B())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(g){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.B())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(e){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.T={};mt.T.log=function(a,b){var e=new Image,g="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[g]=e;e.onload=e.onerror=e.onabort=function(){e.onload=e.onerror=e.onabort=q;e=window[g]=q;b&&b(a)};e.src=a};mt.L={};
mt.L.oa=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(e){}return a};
mt.L.Ea=function(a,b,e,g,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+e+'" height="'+g+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+e+'" height="'+g+'" src="'+b+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.i=function(a,b){var e=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return e?e[3]:q};mt.url.Ia=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.la=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.O=function(a){return(a=mt.url.la(a))?a.replace(/:\d+$/,""):a};mt.url.Ha=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.n={Ja:"http://tongji.baidu.com/hm-web/welcome/ico",J:"hm.baidu.com/hm.gif",X:"baidu.com",ra:"hmmd",sa:"hmpl",qa:"hmkw",pa:"hmci",ta:"hmsr",m:0,j:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",La:0,ba:6E5,ca:10,M:1024,aa:1,w:2147483647,U:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={k:{},d:function(a,e){this.k[a]=this.k[a]||[];this.k[a].push(e)},q:function(a,e){this.k[a]=this.k[a]||[];for(var g=this.k[a].length,k=0;k<g;k++)this.k[a][k](e)}};return h.r=a})();
(function(){function a(a,g){var k=document.createElement("script");k.charset="utf-8";b.e(g,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=q,g()}:k.onload=function(){g()});k.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(k,m)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.o,b=mt.event,e=mt.h,g=h.n,k=[],m={V:function(){c.ctrk&&(b.d(document,"mouseup",m.$()),b.d(window,"unload",function(){m.z()}),setInterval(function(){m.z()},g.ba))},$:function(){return function(a){a=m.ia(a);if(""!==a){var d=(g.protocol+"//"+g.J+"?"+h.b.S().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;d+(g.w+"").length>g.M||(d+encodeURIComponent(k.join(",")+(k.length?",":"")).length+(g.w+"").length>g.M&&m.z(),k.push(a),(k.length>=g.ca||/t:a/.test(a))&&m.z())}}},
ia:function(b){if(0===g.aa){var d=b.target||b.srcElement,f=d.tagName.toLowerCase();if("embed"==f||"object"==f)return""}e.va?(d=Math.max(document.documentElement.scrollTop,document.body.scrollTop),f=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),f=b.clientX+f,d=b.clientY+d):(f=b.pageX,d=b.pageY);var l=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:f-=l/2;break;case 2:f-=l}f="{x:"+f+",y:"+d+",";d=b.target||b.srcElement;
return f=(b="a"==d.tagName.toLowerCase()?d:a.ha(d))?f+("t:a,u:"+encodeURIComponent(b.href)+"}"):f+"t:b}"},z:function(){0!==k.length&&(h.b.a.et=2,h.b.a.ep="["+k.join(",")+"]",h.b.g(),k=[])}};h.r.d("pv-b",m.V);return m})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.C.ma()+","+h.C.ka();h.b.g()}}function b(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);d="undefined"==typeof a?p:a;if((!n||!f)&&d&&l)t=p,s=+new Date;else if(n&&f&&(!d||!l))t=r,u+=+new Date-s;n=d;f=l;x=setTimeout(b,100)}function e(f){var a=document,l="";if(f in a)l=f;else for(var d=["webkit","ms","moz","o"],b=0;b<d.length;b++){var s=d[b]+f.charAt(0).toUpperCase()+f.slice(1);if(s in a){l=
s;break}}return l}function g(f){if(!("focus"==f.type||"blur"==f.type)||!(f.target&&f.target!=window))l="focus"==f.type||"focusin"==f.type?p:r,b()}var k=mt.event,m=h.r,n=p,d=p,f=p,l=p,v=+new Date,s=v,u=0,t=p,w=e("visibilityState"),y=e("hidden"),x;b();(function(){var f=w.replace(/[vV]isibilityState/,"visibilitychange");k.d(document,f,b);k.d(window,"pageshow",b);k.d(window,"pagehide",b);"object"==typeof document.onfocusin?(k.d(document,"focusin",g),k.d(document,"focusout",g)):(k.d(window,"focus",g),
k.d(window,"blur",g))})();h.C={ma:function(){return+new Date-v},ka:function(){return t?+new Date-s+u:u}};m.d("pv-b",function(){k.d(window,"unload",a())});return h.C})();
(function(){var a=mt.lang,b=h.n,e=h.load,g={ua:function(g){if((void 0===window._dxt||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var m=h.b.F();e([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),g)}},Da:function(b){if(a.e(b,"String")||a.e(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.da=g})();
(function(){function a(f){for(var b in f)if({}.hasOwnProperty.call(f,b)){var d=f[b];e.e(d,"Object")||e.e(d,"Array")?a(d):f[b]=String(d)}}function b(f){return f.replace?f.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):f}var e=mt.lang,g=mt.l,k=h.n,m=h.r,n=h.da,d={P:q,p:[],A:0,Q:r,init:function(){d.c=0;d.P={push:function(){d.I.apply(d,arguments)}};m.d("pv-b",function(){d.ea();d.fa()});m.d("pv-d",d.ga);m.d("stag-b",function(){h.b.a.api=d.c||d.A?d.c+"_"+d.A:""});m.d("stag-d",function(){h.b.a.api=
0;d.c=0;d.A=0})},ea:function(){var f=window._hmt;if(f&&f.length)for(var a=0;a<f.length;a++){var b=f[a];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(d.c|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))d.c|=2,window._bdhm_autoPageview=b}}},fa:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var f=window._hmt;if(f&&f.length)for(var a=0,b=f.length;a<b;a++)e.e(f[a],
"Array")&&"_trackEvent"!==f[a][0]&&"_trackRTEvent"!==f[a][0]?d.I(f[a]):d.p.push(f[a]);window._hmt=d.P}},ga:function(){if(0<d.p.length)for(var a=0,b=d.p.length;a<b;a++)d.I(d.p[a]);d.p=q},I:function(a){if(e.e(a,"Array")){var b=a[0];if(d.hasOwnProperty(b)&&e.e(d[b],"Function"))d[b](a)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){d.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.G?(h.b.a.nv=0,h.b.a.st=4):h.b.G=p;var b=h.b.a.u,e=h.b.a.su;h.b.a.u=k.protocol+"//"+document.location.host+
a[1];d.Q||(h.b.a.su=document.location.href);h.b.g();h.b.a.u=b;h.b.a.su=e}},_trackEvent:function(a){2<a.length&&(d.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.g())},_setCustomVar:function(a){if(!(4>a.length)){var l=a[1],e=a[4]||3;if(0<l&&6>l&&0<e&&4>e){d.A++;for(var s=(h.b.a.cv||"*").split("!"),g=s.length;g<l-1;g++)s.push("*");s[l-1]=e+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.xa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?k.protocol+"//"+window.location.host+a[1]:a[1],d.Q=p)},_trackOrder:function(b){b=b[1];e.e(b,"Object")&&(a(b),d.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=g.stringify(b),h.b.g())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])d.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.g()},_trackRTPageview:function(b){b=
b[1];e.e(b,"Object")&&(a(b),b=g.stringify(b),512>=encodeURIComponent(b).length&&(d.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(e.e(b,"Object")){a(b);b=encodeURIComponent(g.stringify(b));var l=function(a){var b=h.b.a.rt;d.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.g();h.b.a.rt=b},m=b.length;if(900>=m)l.call(this,b);else for(var m=Math.ceil(m/900),s="block|"+Math.round(Math.random()*k.w).toString(16)+"|"+m+"|",u=[],t=0;t<m;t++)u.push(t),u.push(b.substring(900*t,900*t+900)),l.call(this,s+u.join("|")),
u=[]}},_setUserId:function(a){a=a[1];n.ua();n.Da(a)}};d.init();h.Y=d;return h.Y})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.G=r,this.init())}var b=mt.url,e=mt.T,g=mt.L,k=mt.lang,m=mt.cookie,n=mt.h,d=mt.localStorage,f=mt.sessionStorage,l=h.n,v=h.r;a.prototype={H:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length},R:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},s:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.R(a,c.dm[d]))return p}else{var f=b.O(a);if(f&&this.H(f,c.dm[d]))return p}return r},F:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.H(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},N:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.R(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},na:function(){if(!document.referrer)return l.j-l.m>c.vdur?1:4;var a=
r;this.s(document.referrer)&&this.s(document.location.href)?a=p:(a=b.O(document.referrer),a=this.H(a||"",document.location.hostname));return a?l.j-l.m>c.vdur?1:4:3},getData:function(a){try{return m.get(a)||f.get(a)||d.get(a)}catch(b){}},setData:function(a,b,e){try{m.set(a,b,{domain:this.F(),path:this.N(),D:e}),e?d.set(a,b,e):f.set(a,b)}catch(l){}},xa:function(a){try{m.set(a,"",{domain:this.F(),path:this.N(),D:-1}),f.remove(a),d.remove(a)}catch(b){}},Ba:function(){var a,b,d,f,e;l.m=this.getData("Hm_lpvt_"+
c.id)||0;13==l.m.length&&(l.m=Math.round(l.m/1E3));b=this.na();a=4!=b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){f=d.split(",");for(e=f.length-1;0<=e;e--)13==f[e].length&&(f[e]=""+Math.round(f[e]/1E3));for(;2592E3<l.j-f[0];)f.shift();e=4>f.length?2:3;for(1===a&&f.push(l.j);4<f.length;)f.shift();d=f.join(",");f=f[f.length-1]}else d=l.j,f="",e=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,l.j);d=l.j==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.s(document.location.href)&&
(""===document.referrer||this.s(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=f;this.a.lv=e},S:function(){for(var a=[],b=0,d=l.U.length;b<d;b++){var f=l.U[b],e=this.a[f];"undefined"!=typeof e&&""!==e&&a.push(f+"="+encodeURIComponent(e))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Ca:function(){this.Ba();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=n.ya;this.a.cl=n.colorDepth+"-bit";
this.a.ln=n.language;this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=g.oa();this.a.v="1.0.85";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.i(a,l.ra)||"";this.a.cp=b.i(a,l.sa)||"";this.a.cw=b.i(a,l.qa)||"";this.a.ci=b.i(a,l.pa)||"";this.a.cf=b.i(a,l.ta)||""},init:function(){try{this.Ca(),0===this.a.nv?this.Aa():this.K(".*"),h.b=this,this.Z(),
v.q("pv-b"),this.za()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));e.log(l.protocol+"//"+l.J+"?"+b.join("&"))}},za:function(){function a(){v.q("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.G=p,this.a.et=0,this.a.ep="",this.g(a)):a()},g:function(a){var b=this;b.a.rnd=Math.round(Math.random()*l.w);v.q("stag-b");var d=l.protocol+"//"+
l.J+"?"+b.S();v.q("stag-d");b.W(d);e.log(d,function(d){b.K(d);k.e(a,"Function")&&a.call(b)})},Z:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),f=-1<document.referrer.indexOf(l.X)?p:r,e=b.i(a,"jn"),g=/^heatlink$|^select$/.test(e);a&&(d.test(a)&&f&&g)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+e+".js?"+this.a.rnd),e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(a,
e))},W:function(a){var b=f.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");f.set("Hm_unsent_"+c.id,b)},K:function(a){var b=f.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?f.set("Hm_unsent_"+c.id,b):f.remove("Hm_unsent_"+c.id))},Aa:function(){var a=this,b=f.get("Hm_unsent_"+
c.id);if(b)for(var b=b.split(","),d=function(b){e.log(l.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.K(b)})},g=0,k=b.length;g<k;g++)d(b[g])}};return new a})();
(function(){var a=mt.o,b=mt.event,e=mt.url,g=mt.l;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var k=+new Date,m=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},n=q;a.wa(function(){n=+new Date});var d=function(){var a,b,d;d=m("navigation");b=m("request");d={netAll:b.start-d.start,netDns:m("domainLookup").value,netTcp:m("connect").value,srv:m("response").start-b.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:m("loadEvent").end-d.start};a=document.referrer;var f=q;b=q;if("www.baidu.com"===(a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[])[2])f=e.i(a,"qid"),b=e.i(a,"click_t");a=f;d.qid=a!=q?a:"";b!=q?(d.bdDom=n?n-b:0,d.bdRun=k-b):(d.bdDom=0,d.bdRun=0);h.b.a.et=87;h.b.a.ep=g.stringify(d);h.b.g()};b.d(window,"load",function(){setTimeout(d,500)})}}catch(f){}})();
(function(){var a=h.n,b={init:function(){try{if("http:"===a.protocol){var b=document.createElement("IFRAME");b.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");b.style.display="none";b.style.width="1";b.style.height="1";b.Fa="0";document.body.appendChild(b)}}catch(g){}}};-1<navigator.userAgent.toLowerCase().indexOf("android")&&b.init()})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a=function(a){if(a.item){for(var b=a.length,e=Array(b);b--;)e[b]=a[b];return e}return[].slice.call(a)},b={click:function(){for(var b=[],f=a(document.getElementsByTagName("a")),f=[].concat.apply(f,a(document.getElementsByTagName("area"))),e=/openZoosUrl\(/,g=0,k=f.length;g<k;g++)e.test(f[g].getAttribute("onclick"))&&b.push(f[g]);return b}},e=function(a,b){for(var e in a)if(a.hasOwnProperty(e)&&b.call(a,e,a[e])===r)return r},g=function(a,
b){return Object.prototype.toString.call(a)==="[object "+b+"]"};window._hmt=window._hmt||[];var k,m="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,b){if(k===b){window._hmt.push(["_trackPageview",m+a]);for(var e=+new Date;500>=+new Date-e;);return r}if(g(b,"Array")||g(b,"NodeList"))for(var e=0,n=b.length;e<n;e++)if(k===b[e]){window._hmt.push(["_trackPageview",m+a+"/"+(e+1)]);for(e=+new Date;500>=+new Date-e;);return r}};(function(a,b,e){a.addEventListener?a.addEventListener(b,e,p):a.attachEvent&&
a.attachEvent("on"+b,e)})(document,"click",function(a){a=a||window.event;k=a.target||a.srcElement;var f={};for(e(b,function(a,b){f[a]=g(b,"Function")?b():document.getElementById(b)});k&&k!==document&&e(f,n)!==r;)k=k.parentNode})}})();})();
